# Generated by Django 3.0.7 on 2020-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
